# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 20

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 30

[[main]]
  name = "Talks"
  url = "talk"
  weight = 40

[[main]]
  name = "Posts"
  url = "post"
  weight = 45
[[main]]
  name = "Media"
  url = "#media"
  weight = 50

[[main]]
  name = "CV"
  url = "files/maria-tackett-cv.pdf"
  weight = 60

