---
title: "From f2f to remote: Part 1 "
subtitle: "How Things Changed in Spring 2020"
author: Maria Tackett
date: "`r Sys.Date()`"
slug: remote-teaching-part-1
categories:
tags:
  - teaching
  - regression
  - remote-learning
summary: Reflection on my experience transitioning to remote leraning in Spring 2020
# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
featured: no
image: 
  caption: 'Caption'
  focal_point: ''
  placement: 2
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


This is a blog post about going from face-to-face (f2f) to remote learning. 

To say this has been quite the semester would be an understatement. In the middle of my spring break, I got the notification that Duke was going to remote learning for the remainder of the semester. Though we were given an extra week to make the transition, it was still quite hectic to say the least. After a few weeks of getting used to the new format; however, I realized it wasnt' all bad. Though I still prefer teaching in-person classes, there were a few things I learned this semester that I want to keep doing in the future. 

That leads me to this post. This is my first blog post (well since my Xanga blog in high school), but I wanted to write it for a couple of reasons: 

1. to share my experience in the hopes that others learn from it. During that week and half of reorienting my class, I found hearing what other instructors found worked/didn't work online was incredibly valuable. Most (if not all) institutions have their summer classes online, and I imagine a lot of institutions will have some online component in the fall. 

2. Per #1, I want to remember my experience this semester, since I'm anticipating having to teach online again in the fall (this is just my hunch; Duke has not made any decision about the fall as the time I'm writing this post). 

[INSERT SOMETHING ABOUT THE TERM REMOTE LEARNING]
I'll use the term remote learning [IS THIS THE TERM?] to distinguish what I did this semester from traditional online classes that take a lot of time and careful thought to develop. 

I've decided to divide this into two parts: 

`r emo::ji("arrow_right")` Part 1: From F2F to Remote

- [The course: Regression Analysis](#sta210)
- [Preparing for remote learning](#preparation)
- [How the course changed](#changes)

`r emo::ji("bulb")` Part 2: Lessons Learned (What I hope to keep / change in the fall)

- [What I want to continue doing](#went_well) - Fix link
- [What I want to change](#to_change) - Fix link
    
## The Course: Regression Analysis {#sta210}

[INSERT A SHORT DESCRIPTION OF THE CLASS - CLASS SIZE AND WHO'S IN IT, WHAT IS COVERED, LABS AND LECTURES]. 

My course was already "technology-ehanced" (also known as digitally-enhanced) [ADD LINK AND FORMAL DEFINTION]. In other words, almost every element of the course as facilitated online, all being anchored by the in-person lecture and labs. To give you can idea of what a technology-enhanced course looks like, here is a description of how students interact what they need for the course:

- [**Course website**](https://www2.stat.duke.edu/courses/Spring20/sta210.001/index.html): Everything needed for the course is accessible from the website. This includes all course content along with links to Sakai, GitHub, and RStudio.  

- **Sakai**: This is Duke's Learning Managment System (LMS). It is the place for all protected content such as grades. A link to Sakai is available on the course website. 

- [**GitHub**](https://github.com/sta210-sp20/): All homework, lab assignments, and the final group project are done using GitHub and RStudio. A private repo is created for each student (or group) that contains an R Markdown template, the data, and a link to the assignment instructions. Students push their updates to the repo as they complete the assignment. I won't go into more detail here, but you can read [INSERT PAPER] to see examples of using GitHub in a variety of statistics courses. 

- [**RStudio**](rstudio.com): Students use RStudio maintained by the unviersity's Office of Information Technology, so they can access RStudio through a web browser. [RStudio Cloud](rstudio.cloud) is a cloud-based platform provided and maintained by RStudio that is another great served-based option if your institution doesn't have RStudio servers. In addition to the benefits discussed in [INSERT MINE and COLIN's PAPER], using a server-based computing platform made the transition to remote teaching smoother (more on that later). 

- [**Gradescope**](https://www.gradescope.com/): Students submit their assignments on Gradescope, an online grading and rubric platform. Students can see their assignment grade, the grading rubric, and comments on Gradescope; it is synced with Sakai, so the assignment grade also gets posted in the gradedbook in Sakai.

Since so much of the course was already operating online, my primary focus during the transition was figuring out how to move the face-to-face interactions from the classroom to a video conference.  In other words, how to do lectures, labs, office hours, and the final group project on Zoom. This meant not only figuring out how to use all the features in Zoom but also how to engage students synchronously and asychronously. 

## Preparing for remote learning {#preparation}

### Student Survey 

One of the first things I did in the transition was make a survey for my students adapted from the [COVID-19 Student Survey](https://twitter.com/ksm_csed/status/1238117765829079041) created by Dr. Kristen Stephens-Martinez. Sending the survey was the most helpful thing I did during the transition for two reasons: 

1. **It helped me get in contact with the students.** This was the most efficient way to try to get in contact with the students, given they were now living all over the world. I gave students about a week to do the survey and reached out individually to those who hadn't completed it by the deadline. By that point, I was able to get in contact with every student in the class. 

2. **It helped me better understand the circumstances students would be in as they finished the semester.** The main pieces of information for planning purposes were the students' 

    `r emo::ji("one")` time zones
    
    `r emo::ji("two")` presumed availablity during lecture and lab times
    
   `r emo::ji("three")` access to reliable internet 
   
    There was also space for students to share any questions or concerns they had about the transition to remote learning. These comments gave perspective about the new realities a lot of students faced and just the general concern about what would happen the rest of the semester. 
    
### Training 

Like a lot of instructors, I had never taught online, so I went to *a lot* training workshops and read almost anything I could find about teaching online classes. Here are some of the resources I used to learn more about teaching online:  

- [Webinar: Teaching online on short notice](https://education.rstudio.com/blog/2020/03/teaching-online-on-short-notice/) by Greg Wilson
- [Workshops by Duke Learning Innovation](https://keepteaching.duke.edu/workshops/)
- [Resources and tips for teaching (with) R remotely](https://education.rstudio.com/blog/2020/03/resources-for-teaching-data-science-and-statistics-remotely/)
- [Penn State STAT Online Program](https://online.stat.psu.edu/statprogram/)

- [Webinar: Teaching R online with RStudio Cloud](https://rstudio.com/resources/webinars/teaching-r-online-with-rstudio-cloud/) by Mine Cetinkaya-Rundel
- [Webinar: Sharing on Short Notice: How to get your materials online with R Markdown](https://rstudio.com/resources/webinars/sharing-on-short-notice-how-to-get-your-materials-online-with-r-markdown/) by Alison Hill and Desiree De Leon.

<!--
While most trainings were more focused on how to use the technology, I did find value in just seeing how other people ran online workshops/courses, and how they utilized some of the different features in Zoom. One the most useful courses I took was by Greg Wilson's [ADD TITLE AND LINK]. I took his RStudio Instructor training online, so I knew he was a great facilitator of online courses, so I was happy to see he had a course for the moment. His course provided a nice bridge between the "how-to" of the technology to the pedagogical elements of teaching online. 
-->

Using these resources gave me enough ideas and strategies that I felt I felt ~~ready~~ less terrified to teach remotely.
 
## f2f to remote {#changes}

Here I'll focus on the major changes I made to adapt some of the f2f components of the course to the new remote environment. I'll just describe the changes here, and in Part 2, I'll discuss what worked and what I'd do differently if/when I teach remotely again. I also made changes to the course policies, the biggest change being around late work, to give students more flexibilty while still maintaining the general courese structure. The changes in course policies are in the [Remote Learning Updates](https://www2.stat.duke.edu/courses/Spring20/sta210.001/covid-19-updates.html).
 
### Lectures 

The biggest change to the semester was the way I conducted lectures. Since this was the main component of the class that relied on in-person interaction (lecture with active-learning activities sprinkled throughout), this was what needed the most attention as I made the transition to remote learning. I ultimately decided to split lectures into two components and create some version of a flipped classroom: 
 
#### Lecture content videos
 
  -Pre-recorded live lecture videos: These were essentially like the traditional lecture, where I recorded videos talking through the lecture slides. There were questions sprinkled throughout where in-class discussion/activites would've gone [LINK TO AN EXAMPLE], so I asked students to pause the video and jot down their thoughts/responses to the actvity questions. The pre-recorded lectures were posted about two days in advance in a discussion thread in Sakai, LMS. Students were told to either write their questions down to ask during the "Live Lecture Session" or to reply to the thread with their questions if they couldn't attend be live for the lecture. I checked the discussion thread before each class, so I could make sure to address the posted questions in the live lecture. 
  
### Live lecture session
This was time I met with the class on Zoom during the scheduled lecture time. I made an agenda for each live lecture [ ADD LINK], so students would know what to expect. I typically started with announcements and asking if there any questions that were posted in the discussion thread or that students posted in the Zoom chat or asked verbally after raising their hand. Some quesitons I answered right away; others I jotted down to come back to later since I knew there'd be a more natural place to answer them. 

    After taking questions,  we basically went through the remaining time walking through an analysis covering the topic. Students could use an Rmd file or rendered HTML to follow-along. I usually talked about the code and more practical elements, since students got the basic terminology and definitions from the pre-recorded lecture. During most live lectures, I randomly split students into breakout rooms to talk about the discussion questions from the videos. 
  
    I popped into a few break out rooms during the discussions (students were told beforehand this would happen), and it was really great. A lot of students had their video on in the breakout rooms and it just made everything feel more energetic than in the larger setting. Even as students came back to the main room, a few would keep their video on. I randomly selected a breakout room to respond to the class. 
    
    Used an iPad with the pencil [WHAT"S THIS CALLED?] and the Goodnotes app as the white board. This worked better for me than Zoom white board, since I often needed to write equations. I also used it write Welcome and point students to the day's notes as they entered the class. I typically started the Zoom live lecture session about 5 minutes early. 
  
    The live lecture sessions were recorded and uploaded into the LMS, so students who were unable to attend live could still access the content. 

## Exam 2
- Midterm 2: I give two in-class paper midterms during the semester where students are allowed to bring one page of handwritten notes. Given the exams would be done remotely, I opted for an open-note, open-book exam. I tried to keep the format as similar to the first exam as possible, so students typed their responses in a Word document of the exam, saved it as a PDF and uploaded their resposes to the LMS. The exam was written to be taken within 75 minutes, but students had 2 hours to take the exam to provide flexibility for any computing issues.

### Video presentations

Students had just begun their final group project [ADD LINK] before the transition, so I gave them the option to continue with the same project in their same groups or do something else. They overwhelmingly decided to stay in their same groups (I think because they had been with these groups since the 3rd week of the semester and had learned to work together). The project stayed largely the same, with the exception of the final presentation. Rather than present in-class, each group recorded a video presentation and uploaded it in a discussion thread in Sakai. I gave groups the option to upload their slides with a written transcript if video wasn't an viable option. Students were randomly assigned three presentations to write and post comments. I'll talk about this more in [SECTION NAME - THINGS TO KEEP WITH LINK], but in summary I really liked this format! 


In Part 2, I'll talk about some of the things that worked and that I plan to continue doing in the fall and other things I want to change.


