---
title: "From f2f to remote: Part 1 `r emo::ji('woman_teacher_medium_dark_skin_tone')`" 
subtitle: "Infrastructure for an undergraduate statistics course"
author: Maria Tackett
date: "`r Sys.Date()`"
slug: f2f-remote-infrastructure
categories:
tags:
  - teaching
  - regression
  - rstudio
  - github
  - spring2020
summary: Technology-supported infrastrcutre for an undergraduate statistics course
featured: no
image: 
  caption: 'Caption'
  focal_point: ''
  placement: 2
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style>
.emph {
font-weight: 850; 
color: #671973;
}
</style>

Spring 2020 was quite the semester (to say the least), so I thought it'd be worth writing about the experience of going from face-to-face (f2f) to "emergency remote" teaching. There's a lot to share, so I'm splitting it into two posts:

`r emo::ji("woman_teacher_medium_dark_skin_tone")` Part 1: The infrastructure for my undergraduate regression course

`r emo::ji("woman_technologist_medium_dark_skin_tone")` Part 2: What changed in the transition to a remote class, including what worked and what didn't work. 

*Note: Like many others, I'm using the term "remote" teaching/learning instead of "online" to differentiate what happened in Spring 2020 from the well-designed online courses that take months of thoughtful and careful planning. 

## The Course: Regression Analysis {#sta210}

Before I talk about the infrastructure, here is a brief description of the course to give you some context:

Regression Analysis is a second-semester undergraduate course focused on analyzing multivariate data using regression models. In addition to learning the statistical methods, a large component of the course is learning how to use R and GitHub to conduct analyses that are reproducible and incorporate version control. A more detailed description of the course is at the top of the [course website](https://www2.stat.duke.edu/courses/Spring20/sta210.001/index.html). 

In Spring 2020, there were 90 students from all years and a variety of majors. The whole class met face-to-face twice a week for lecture, and smaller labs (30 students each) met once a week. Aside from these meetings, the course was primarily managed online. As you might expect, the lectures and labs changed the most after the transition, but the rest of the course remained largely unchanged given the online supported infrastructure already put in place. I'll talk more about the changes in Part 2, but for now I'll focus on the infrastructure.

## Infrastructure

- [Insert a sketch of the course infrastructure]

In short, the infrastructure for the course can be described as "online supported", i.e. most of the course is facilitated online and is anchored by in-person lectures and labs. I based this infrastructure on the one described in [Data Science in a Box](https://datasciencebox.org/infrastructure/), where you can find more detail about how to set up the various components described below. 

### Materials 

- <font class = "emph">Course website</font>: The [course website](https://www2.stat.duke.edu/courses/Spring20/sta210.001/index.html) is the central hub for the course. This is the place where students can access anything they need including the syllabus, course schedule, lecture slides, and assignment instructions from the website. It also includes links to the other platforms we use (e.g. Sakai, GitHub). I encourage students to bookmark the course website, since it is the one-stop shop for everything they need in the course. 

- <font class = "emph">Learning Management System (LMS)</font>: All protected content, such as grades, are put in the LMS. It also includes links to the course schedule, syllabus, and the platforms mentioned below, in case students would rather navigate the course through the LMS rather than the website. 

### Assignments

- <font class = "emph">GitHub</font>: All homework, lab assignments, and the final group project are done using GitHub and RStudio. An ["organization"](http://www.github.com/sta210-sp20) is created for the course on GitHub and is connected to GitHub Classroom so students' work remains private (only visible to the student and the teaching team). For each assignment, I create a starter **repo**sitory, i.e. directory that contains an R Markdown template, the data, and a link to the assignment instructions. I use the [ghclass R package](https://rundel.github.io/ghclass/) to make each student or group their own private copy of the starter repo. Students connect their repo to a project in RStudio, where they work on the assignment, and "push" their results to GitHub as they work. I'll refrain from going down the GitHub rabbit hole, but here are some good resources for using GitHub in your course: 
    - [*Reproducible Workflows: R Markdown, Git, GitHub*](https://rstudio-conf-2020.github.io/design-ds-classroom/materials/05-github/slides/05-github.html#1)
    - [*Implementing version control with Git as a learning objective in statistics courses*](https://arxiv.org/abs/2001.01988)
    - [*Using GitHub Classroom To Teach Statistics*](https://amstat.tandfonline.com/doi/full/10.1080/10691898.2019.1617089#.XtbPQBNKgdU)

<br>

- <font class = "emph">RStudio</font>: Students use RStudio hosted in Docker containers maintained by the university's Office of Information Technology. [RStudio Cloud](rstudio.cloud) is a cloud-based platform provided and maintained by RStudio that is another nice server-based option. One of the primary benefits of having students use a server-based version of RStudio is they access through a web browser, so they can use RStudio on almost any device, including tablets and Chromebooks. The paper [*Infrastructure and tools for teaching computing throughout the statistical curriculum*](https://peerj.com/preprints/3181/) discusses many of the other benefits of having students used RStudio through a server (rather than local installations).

- <font class = "emph">Gradescope</font>: Students submit their assignments on [Gradescope](https://www.gradescope.com/), an online grading and rubric platform. Not only does it make grading quicker and more consistent, but it makes it easy for students to see the feedback on their assignments. It can sync with numerous LMS, so the grades can easily be posted in the gradebook in the LMS. The talk [*AI Assisted Fair and Efficient Grading in the Statistics and Data Science Classrooms*](https://www.causeweb.org/cause/ecots/ecots20/breakouts/8) provides a good introduction to using Gradescope for statistics assignments.

If you're curious how all these pieces connect, the slides from the talk [*Using GitHub and RStudio to facilitate authentic learning experiences in a regression analysis course*](https://github.com/matackett/talks/blob/master/presentations/wsds-2019.pdf) show the work flow for a homework or lab assignment.

### Communication

- <font class = "emph">Student Q&A</font>: We use [Piazza](https://piazza.com/), an online Q&A platform to post questions about assignments and the course content. Anyone in the course can respond to the question, so this gives students an opportunity to answer each others' questions. It also keeps me and the teaching assistants from answering the same questions multiple times. 

- <font class = "emph">Teaching Team Communication</font>: I use [Slack](https://slack.com/) to communicate with the teaching team. We have multiple channels - *general, hw, labs, exams, project, office-hours* - to help organize the conversation. Aside from an initial email at the beginning of the semester, all communication with the teaching team occurs in Slack. This helps keep everything in one place, and the more relaxed nature of Slack (compared to email) encourages more frequent discussion and idea sharing.

<br>

That sums up the course infrastructure. In [Part 2](../), I'll share how the course changed when we transitioned to remote teaching. *Spoiler alert: the online supported infrastructure made the transition much smoother.*

