---
title: "From f2f to remote: Part 2 `r emo::ji('woman_technologist_medium_dark_skin_tone')`" 
subtitle: "Transition to remote learning"
author: Maria Tackett
date: "`r Sys.Date()`"
slug: f2f-remote-transition
categories:
tags:
  - teaching
summary: Transition to remote learning
# Placement options: 1 = Full column width, 2 = Out-set, 3 = Screen-width
# Focal point options: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
featured: yes
image: 
  caption: ""
  focal_point: ''
  placement: 2
  preview_only: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This is the second of a two-part series about my undergraduate regression analysis course in Spring 2020. In [Part 1](../f2f-remote-infrastructure), I described the infrastructure for the course, and in this post, I'll discuss what changed when we transitioned to remote learning mid-semester. 

Because a lot of the course infrastructure was already online (e.g. materials, assignments, etc.), the major changes to the course were in the face-to-face (f2f) elements, such as the lectures and labs. These f2f elements are the focus for this post. 

## Preparing to go remote {#preparation}

### Student Survey

One of the first things I did in the transition was make a survey for my students adapted from the [COVID-19 Student Survey](https://twitter.com/ksm_csed/status/1238117765829079041) created by Dr. Kristen Stephens-Martinez. Sending the survey was the most helpful thing I did during the transition to remote learning for two reasons:

1. **It helped me get in contact with the students.** This was the most efficient way to try to get in contact with the students, given they were now living all over the world. I asked the students to complete the survey within a week; after the deadline, I reached out individually to students who hadn't returned the survey. By that point, I was able to get in contact with every student in the class.

2. **It helped me better understand each student's new learning environment.** The primary pieces of information I asked for were the student's

    - time zone
    - presumed availability during lecture and lab times
    - access to reliable internet

    There was also an optional part of the survey for students to share any questions or concerns they had about the transition to remote learning. This helped me better understand some of the other challenges some students would face aside from time zone and internet issues. It also helped me better understand some of the general concerns students had, so I was able to better address those as I planned for the rest of the semester.

### Training

Like a lot of instructors, I had never taught online, so I went to *a lot* training workshops and read almost anything I could find about teaching remotely. Here are just a few of the resources I used to learn more about teaching remotely. 

- [Webinar: Teaching online on short notice](https://education.rstudio.com/blog/2020/03/teaching-online-on-short-notice/) by Greg Wilson
- [Keep Teaching Workshops by Duke Learning Innovation](https://keepteaching.duke.edu/workshops/)
- [Resources and tips for teaching (with) R remotely](https://education.rstudio.com/blog/2020/03/resources-for-teaching-data-science-and-statistics-remotely/)

Penn State has an established [online statistics program](https://online.stat.psu.edu/statprogram/), so I also used their courses as I adapted my class to the new remote format. 


## What changed {#changes}

Using these resources gave me enough ideas and strategies that I felt ~~completely ready~~ less terrified to teach remotely.

Since a lot of the course infrastructure was [already online](../f2f-remote-infrastructure), I focused a majority of my effort on adapting the f2f components - lectures, labs, exams, and final presentations. I also made changes to the course policies, the most substantial being around late work, to give students more flexibility but still help them keep up with the course material. The changes to course policies are in the [Remote Learning Updates](https://www2.stat.duke.edu/courses/Spring20/sta210.001/covid-19-updates.html).



### Lectures

As with a lot of classes, the lectures changed the most after the transition. During the f2f lecture, I mostly talked through lecture slides and had small group activities and polling questions throughout. As I thought about reorienting the lectures for Zoom, I tried to balance the desire to

- continue meeting for synchronously for lecture.

- not disadvantage students who couldn't attend the synchronous lecture.

- make the synchronous lectures interactive (or at least as interactive as 90 people on Zoom can be).

Taking these considerations into account, I landed on using a "flipped classroom" format where students watched *lecture content videos* on their own before lecture, and the *live lecture session* was used to answer questions and work through examples. I used the language *lecture content videos* and *live lecture session* instead of "asynchronous" and "synchronous", to help students more easily keep track of the new format. 

### Lecture content videos (asynchronous)

Before each live lecture session, students watched pre-recorded videos covering the content. In these videos, I talked over lecture slides and included periodic questions to help students think about what they just heard. I also used these questions as the basis for the live lecture session. Since I just used Zoom to record the lectures with no editing software, I told students to "pause the video, write down your response to the questions, and we'll discuss them during the live lecture session." I also encouraged students to write down any questions they had about the content from the videos, so we could discuss them during the live lecture session.

The pre-recorded lectures were posted about two days in advance in a discussion forum in Sakai, the learning management system (LMS). I used the discussion forum, so students unable to attend the lecture session could post their questions directly under the video. I checked the discussion thread before each live lecture session, so I could address the questions posted in the discussion during the live lecture session.

### Live lecture session (synchronous)

The live lecture sessions were held using Zoom. I started the Zoom session about 5 minutes before it started with a screen saying "Welcome to STA 210" and the .Rmd file we were going to go over during the session. Once class started, I answered questions about the content videos (including those from the discussion thread). Students in the live session could post their questions in the chat use Zoom's raise hand feature and I would call on them. I answered most questions right away; others I jotted down to address later, since I knew the material would come up as we talked through examples. 

The remainder of the time was going through an example that applied the concepts from the lecture videos. I used the same data that was presented in the lecture videos, so students were already familiar with the data set and analysis questions. I focused on the code and the practical considerations when applying the concpets in an anaylysis, since students got the basic terminology and definitions from the pre-recorded lecture videos. As we went through the example, students were randomly assigned to breakout rooms to discuss the questions that were originally presented in the lecture videos. 

I visited a few break out rooms during the discussions (students were told beforehand this would happen), and it was definitely the best part of the live lecture sessions. A lot of students turned their video on in the breakout rooms, which made everything feel more energetic than in the larger setting where most, if not all, students had their video off. Even as students came back to the large discussion, the environment felt more lively than before the first discussion. I typically called on students from one or two of the rooms, and one student from each room would share their conclusions with the class.

The live lecture sessions were recorded and uploaded to the LMS, so students who were unable to attend live still had access to the content. 

A few other things that were helpful during lecture: 

- I made an [agenda](https://www2.stat.duke.edu/courses/Spring20/sta210.001/slides/lec-slides/live-lecture-apr01.html) for each live session. This was not only helpful for students, but it helped keep track of the new lecture structure.

- Used an iPad + pencil and the [GoodNotes app](https://www.goodnotes.com/) as a white board. This was easier for me than the Zoom whiteboard, since I write a lot of equations. I also used this to write my welcome note. 

- I sent a recap email after each live lecture session that pointed students to the lecture recording, upcoming assignment deadlines, and other announcements and resources.

### Labs

The structure of labs remained similar to the structure before the transition. The lab TA did a brief introduction to the day's lab, then students worked with their groups using the Zoom breakout rooms. The lab TAs visited each breakout at some point during the lab session. 

Students were already used to using GitHub for collaboration, so they completed lab assignments using a similar workflow as before.

### Exam

I typically give two in-class exam where students are allowed to bring one page of handwritten notes. Given the exams would be completed remotely, I opted for an open-note, open-book exam. More specifically, students could use any resource except for consulting to other people. I tried to keep the format as similar to the first exam as possible, so students downloaded a Word document of the exam from the LMS, typed their responses in the document under each question, saved it as a PDF, and uploaded their responses to the LMS. The exam was designed to be be completed within 75 minutes (the length of a class period), but students were allotted for the exam to provide flexibility in case of computing issues.

A practice exam was given to students using the same format, so they had a week to practice and ask questions before the actual exam.

### Video presentations

Students had started the [final project](https://www2.stat.duke.edu/courses/Spring20/sta210.001/project/project.html) right before the transition to remote learning, so I gave them the option to continue with the same project in their same groups or do something else. They overwhelmingly decided to work on the original project in the same groups. (This is likely because they had been working in these groups since the 3rd week of the semester and had learned to work together). 

The project remained mostly the same, with the exception of the final presentation. Rather than present in class, each group recorded a video presentation and uploaded it to a discussion thread in the LMS. If groups were unable to make a video, they had the option to upload their slides along with a script of what they would say in a presentation Students were randomly assigned three presentations to watch, and they were required to post a relevant and thoughtful question about the presentation. I'll talk about this more in the next section, but in summary I really liked this format!

## Lessons learned

Here are a few things that worked in the spring and things I want to change and improve in the Fall. 

### What worked

`r emo::ji("white_check_mark")` *Having an online-supported infrastructure.* I describe the course infrastructure in [Part 1](../f2f-remote-infrastructure). This infrastructure works well in the remote and f2f class. 

`r emo::ji("white_check_mark")` *Sending the survey*. The student survey was extremely helpful, so I could better plan the course to accommdate a variety of new learning environments.
    
`r emo::ji("white_check_mark")` *Having a flipped classroom format for the lectures*. Being able to spend the lecture answering questions and working through examples was a much better use of the time than going over lecture slides. I also heard from a few students that they liked having the lecture content videos, so they could replay any content they needed to review. 
    
`r emo::ji("white_check_mark")` *Using Zoom breakout rooms*. As I mentioned earlier, these were fantastic during the live lectures. It gave students an opportunity to talk with each other in small groups and really helped break the monotony of being on Zoom. 

`r emo::ji("white_check_mark")` *Having students record video presentations and post questions in the discussion forum.* Students were thoughtful in how they organized their presentation, and some groups even included creative technical elements in the videos. Because we weren't constrained by time, as we are during in-class presentations, students had more time to develop thoughtful questions that demonstrated their understanding of the course material. This format also gave every student an opportunity to share their thoughts and ask questions rather than a select few. 

  In the fall, I will also ask each group to respond to a few of the questions they were asked. 


### What needs some work

`r emo::ji("hammer_and_wrench")` *Building community in a large online class.* By the time we moved online in the spring, there was already a community established from the first half of the semester. That won't be the case in the fall, so I would like to figure out ways to help students connect remotely. 

`r emo::ji("hammer_and_wrench")` *Helping students manage teamwork remotely*. Teams had been working together for a few weeks by the time we moved remote in the spring, so they were generally able to just adapt their workflow for the new environment. Teams in the fall will do all work remotely and will likely never meet f2f, so they will need additional help figuring out group workflow and dynamics. 

`r emo::ji("hammer_and_wrench")` *Managing office hours.* I used the waiting room feature in Zoom, so I could work with students one at a time. This sometimes resulted in students waiting a while to receive help when they actually had the same questions as the student I was working with. In the fall, I may try a tool such as [My Digital Hand](https://mydigitalhand.org/), where students indicate what they want to discuss in office hours. This way, I can help groups of students who have the same questions, similar to how I would in f2f office hours. 

<br>

I would love to hear what ideas you have for teaching online or in a hybrid format, especially for large classes. In the meantime, I'll leave you with some [remote teaching tips](https://preparingtoteach.org/post/recap-remote-teaching/]) from Preparing to Teach.
